'use strict';

const fetch = require('node-fetch');

const DEFAULT_BASE = process.env.DEEPSEEK_BASE_URL || 'https://api.deepseek.com';
const DEFAULT_MODEL = process.env.DEEPSEEK_MODEL || 'deepseek-chat';

const SYSTEM_PROMPT = `You are an email-quality classifier. You receive a JSON list of candidate
email addresses (each with the page URL it was scraped from and a short context snippet) and
return a JSON object indicating which addresses look like real, deliverable, human or business
mailboxes — not autogenerated tracking IDs, not example/test/dummy addresses, not fake
filenames mistakenly parsed as emails, not honeypot/spamtrap-looking strings.

Strict rules:
- Output ONLY valid JSON, no prose, no markdown fences.
- Schema: {"results":[{"email":"x@y.com","real":true|false,"confidence":0.0-1.0,"reason":"…"}]}
- "real" = true means you'd be comfortable putting this in a CRM as a contact.
- Reject obvious junk: noreply@, donotreply@, mailer-daemon@, postmaster@, abuse@, anything
  that ends in an image/file extension (e.g. logo@2x.png), random hex strings, repeated chars,
  or addresses whose local part is the same as a UI label like "image", "icon", "sprite".
- Be skeptical of disposable / temporary / role-only mailboxes; only mark them real if context
  suggests genuine intent (e.g. info@, contact@, sales@ on a real business site is fine).`;

async function chat(messages, { apiKey, model = DEFAULT_MODEL, baseUrl = DEFAULT_BASE, temperature = 0 } = {}) {
  if (!apiKey) throw new Error('DEEPSEEK_API_KEY missing');
  const res = await fetch(`${baseUrl}/v1/chat/completions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({ model, messages, temperature, response_format: { type: 'json_object' } }),
  });
  if (!res.ok) {
    const txt = await res.text().catch(() => '');
    throw new Error(`DeepSeek ${res.status}: ${txt.slice(0, 200)}`);
  }
  const json = await res.json();
  return json.choices?.[0]?.message?.content || '';
}

function chunk(arr, size) {
  const out = [];
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
  return out;
}

async function validateEmails(candidates, { apiKey, batchSize = 40, log = () => {} } = {}) {
  if (!apiKey) {
    log('DeepSeek API key not set — skipping AI validation, returning all candidates as unverified');
    return candidates.map((c) => ({ ...c, real: null, confidence: null, reason: 'no-deepseek-key' }));
  }
  if (!candidates.length) return [];
  const results = [];
  const batches = chunk(candidates, batchSize);
  for (let i = 0; i < batches.length; i++) {
    const batch = batches[i];
    log(`DeepSeek validating batch ${i + 1}/${batches.length} (${batch.length} emails)`);
    const userPayload = {
      candidates: batch.map((c) => ({
        email: c.email,
        sources: (c.sources || []).slice(0, 3),
        contexts: (c.contexts || []).slice(0, 3),
      })),
    };
    let parsed;
    try {
      const raw = await chat([
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: JSON.stringify(userPayload) },
      ], { apiKey });
      parsed = JSON.parse(raw);
    } catch (err) {
      log(`DeepSeek batch ${i + 1} failed: ${err.message}`);
      for (const c of batch) results.push({ ...c, real: null, confidence: null, reason: `deepseek-error: ${err.message}` });
      continue;
    }
    const byEmail = new Map();
    for (const r of parsed.results || []) byEmail.set(String(r.email).toLowerCase(), r);
    for (const c of batch) {
      const r = byEmail.get(c.email.toLowerCase());
      results.push({
        ...c,
        real: r ? !!r.real : null,
        confidence: r && typeof r.confidence === 'number' ? r.confidence : null,
        reason: r?.reason || 'not-returned-by-model',
      });
    }
  }
  return results;
}

module.exports = { validateEmails, chat };
